# Generated by Django 3.0.8 on 2020-08-02 23:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre del Maestro')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor activo / No activo')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoría activada / No activada')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('descripcion', models.CharField(max_length=220, verbose_name='Datos de Búsqueda')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('volumen', models.CharField(max_length=100, verbose_name='Volumen')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación Física')),
                ('fecha_origen', models.DateField(verbose_name='Fecha')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('fecha_publicacion', models.DateField(auto_now=True, verbose_name='Fecha de publicación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
